services:
  app:
    image: ahmadsamehh/mini-node-app:latest
    container_name: bfgf-container
    env_file:
      - .env
    expose:
      - "6800" # Expose port 6800 to other containers and should match the .env and caddy config #
    restart: always
